# Generated by Django 5.1.2 on 2024-10-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_tanggal_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_status',
            field=models.IntegerField(choices=[(1, 'Should Buy'), (2, 'Interested'), (3, 'Maybe Later')], default=3),
        ),
    ]
