# Generated by Django 5.1.2 on 2024-12-22 07:29

from django.db import migrations, models
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "products.json")

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('kerajinan_tangan', 'Kerajinan Tangan'), ('makanan_minuman', 'Makanan/Minuman'), ('pakaian', 'Pakaian'), ('lain_lain', 'Lain - lain')], max_length=50),
        ),
    ]
