# Generated by Django 5.1.2 on 2024-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(choices=[('kerajinan_tangan', 'Kerajinan Tangan'), ('makanan_minuman', 'Makanan/Minuman'), ('pakaian', 'Pakaian'), ('lain_lain', 'Lain - lain')], max_length=50),
        ),
    ]
