# Generated by Django 5.1.2 on 2024-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_owner'),
        ('catalog', '0007_remove_product_owner'),
    ]

    operations = [
    ]
